source 'https://rubygems.org' 

gem 'capistrano', '~> 3.17.3'
gem 'capistrano-laravel', '~> 1.2.3'
gem 'ed25519', '~> 1.3.0'
gem 'bcrypt_pbkdf', '~> 1.0'
gem 'uri', '~> 0.12.1'
gem 'net-ssh', '~> 7.2.0'
